# Generated by Django 4.2.7 on 2023-12-04 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('Fuel_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('Station_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FuelPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('AmountOfFuel', models.PositiveIntegerField()),
                ('Fuel_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainServer.fuel')),
                ('Station_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainServer.fuelstation')),
            ],
        ),
    ]
